/**
 * Architecture Diagram Schema
 * 
 * This defines the structure for JSON-based cloud architecture diagrams
 * that will be generated by the AI and rendered by our custom DiagramComponent.
 */

/**
 * @typedef {'networking' | 'presentation' | 'application' | 'data' | 'security' | 'operations'} LayerType
 * Represents the architectural layer where a component resides
 * - networking: CDN, Load Balancers, API Gateways, VPN, DNS
 * - presentation: Web servers, Frontend applications
 * - application: Application servers, Microservices, Functions
 * - data: Databases, Caches, Object Storage, Data Lakes
 * - security: IAM, Key Management, Firewalls, Security Monitoring
 * - operations: Monitoring, Logging, CI/CD, Automation
 */

/**
 * @typedef {Object} DiagramNode
 * @property {string} id - Unique identifier for the node
 * @property {string} label - Display name for the component (keep short, max 15 chars)
 * @property {string} layer - Which architectural layer this belongs to
 * @property {string} [type] - Service type (e.g., 'compute', 'database', 'storage', 'networking')
 * @property {string} [icon] - Lucide icon name (e.g., 'Server', 'Database', 'Cloud', 'Shield')
 * @property {string} [description] - Detailed description for tooltips
 * @property {string} [cost] - Monthly cost estimate for this component
 */

/**
 * @typedef {Object} DiagramConnection
 * @property {string} from - Source node ID
 * @property {string} to - Target node ID
 * @property {string} [label] - Connection description (e.g., 'HTTPS', 'SQL', 'API')
 * @property {string} [type] - Connection type: 'solid' (default), 'dashed', 'bidirectional'
 */

/**
 * @typedef {Object} ArchitectureDiagram
 * @property {string} name - Architecture name/title
 * @property {'aws' | 'azure' | 'gcp' | 'multi-cloud'} provider - Cloud provider for theming
 * @property {DiagramNode[]} nodes - All components in the architecture
 * @property {DiagramConnection[]} connections - All connections between components
 */

/**
 * Validates that a diagram object conforms to the schema
 * @param {ArchitectureDiagram} diagram - The diagram to validate
 * @returns {Object} Validation result with isValid boolean and errors array
 */
export function validateDiagram(diagram) {
  const errors = [];

  if (!diagram) {
    return { isValid: false, errors: ['Diagram is null or undefined'] };
  }

  if (!diagram.name || typeof diagram.name !== 'string') {
    errors.push('Diagram must have a name');
  }

  if (!['aws', 'azure', 'gcp', 'multi-cloud'].includes(diagram.provider)) {
    errors.push('Provider must be aws, azure, gcp, or multi-cloud');
  }

  if (!Array.isArray(diagram.nodes) || diagram.nodes.length === 0) {
    errors.push('Diagram must have at least one node');
  }

  if (!Array.isArray(diagram.connections)) {
    errors.push('Connections must be an array');
  }

  // Validate nodes
  if (Array.isArray(diagram.nodes)) {
    diagram.nodes.forEach((node, index) => {
      if (!node.id) errors.push(`Node ${index} missing id`);
      if (!node.label) errors.push(`Node ${index} missing label`);
      if (!node.layer) errors.push(`Node ${index} missing layer`);
      if (!['networking', 'presentation', 'application', 'data', 'security', 'operations'].includes(node.layer)) {
        errors.push(`Node ${index} has invalid layer: ${node.layer}`);
      }
    });
  }

  // Validate connections reference valid nodes
  if (Array.isArray(diagram.connections) && Array.isArray(diagram.nodes)) {
    const nodeIds = new Set(diagram.nodes.map(n => n.id));
    diagram.connections.forEach((conn, index) => {
      if (!nodeIds.has(conn.from)) {
        errors.push(`Connection ${index} references non-existent node: ${conn.from}`);
      }
      if (!nodeIds.has(conn.to)) {
        errors.push(`Connection ${index} references non-existent node: ${conn.to}`);
      }
    });
  }

  return {
    isValid: errors.length === 0,
    errors
  };
}

/**
 * Example architecture diagram for reference
 */
export const exampleDiagram = {
  name: "E-commerce Platform",
  provider: "aws",
  nodes: [
    {
      id: "cdn",
      label: "CloudFront",
      layer: "networking",
      type: "cdn",
      icon: "Globe",
      description: "Content Delivery Network for global distribution",
      cost: "$50"
    },
    {
      id: "lb",
      label: "ALB",
      layer: "networking",
      type: "loadbalancer",
      icon: "Network",
      description: "Application Load Balancer",
      cost: "$25"
    },
    {
      id: "web",
      label: "ECS Web",
      layer: "application",
      type: "compute",
      icon: "Server",
      description: "Web tier containers",
      cost: "$150"
    },
    {
      id: "api",
      label: "Lambda API",
      layer: "application",
      type: "compute",
      icon: "Zap",
      description: "Serverless API functions",
      cost: "$30"
    },
    {
      id: "cache",
      label: "ElastiCache",
      layer: "application",
      type: "cache",
      icon: "Cpu",
      description: "Redis cache for sessions",
      cost: "$40"
    },
    {
      id: "db",
      label: "RDS",
      layer: "data",
      type: "database",
      icon: "Database",
      description: "PostgreSQL database",
      cost: "$100"
    },
    {
      id: "s3",
      label: "S3",
      layer: "data",
      type: "storage",
      icon: "HardDrive",
      description: "Object storage",
      cost: "$20"
    },
    {
      id: "iam",
      label: "IAM",
      layer: "security",
      type: "security",
      icon: "Shield",
      description: "Identity management",
      cost: "$0"
    }
  ],
  connections: [
    { from: "cdn", to: "lb", label: "HTTPS" },
    { from: "lb", to: "web", label: "HTTP" },
    { from: "web", to: "api", label: "Internal API" },
    { from: "api", to: "cache", label: "Redis" },
    { from: "api", to: "db", label: "SQL" },
    { from: "api", to: "s3", label: "S3 API" },
    { from: "iam", to: "api", label: "Auth", type: "dashed" }
  ]
};
